"# wtf-file-gvimrc
" highlight Normal guifg=white guibg=black

au! GUIEnter * set visualbell t_vb=

if has("win32")
    set guifont=Consolas:h11
    au! GUIEnter * simalt ~x
else
    set guifont=UbuntuMono\ NF:h11
endif

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L

if filereadable(expand("~/.gvimrc-local.vim"))
    source ~/.gvimrc-local.vim
endif

function! FontSizePlus ()
    let l:gf_size_whole = matchstr(&guifont, '\(:h\)\@<=\d\+$')
    let l:gf_size_whole = l:gf_size_whole + 1
    let l:new_font_size = ':h'.l:gf_size_whole
    let &guifont = substitute(&guifont, ':h\d\+$', l:new_font_size, '')
endfunction

function! FontSizeMinus ()
    let l:gf_size_whole = matchstr(&guifont, '\(:h\)\@<=\d\+$')
    let l:gf_size_whole = l:gf_size_whole - 1
    let l:new_font_size = ':h'.l:gf_size_whole
    let &guifont = substitute(&guifont, ':h\d\+$', l:new_font_size, '')
endfunction

nnoremap <c-kPlus> :call FontSizePlus()<CR>
nnoremap <c-kMinus> :call FontSizeMinus()<CR>
