"# wtf-file-gvimrc

au! GUIEnter * set visualbell t_vb=

"https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
set guifont=DejaVuSansMono_NF:h11,DejaVuSansMono_Nerd_Font_Mono:h11,Consolas:h12,UbuntuMono\ NF:h11

if has("win32")
    au! GUIEnter * simalt ~x
endif

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L

if filereadable(expand("~/.gvimrc-local.vim"))
    source ~/.gvimrc-local.vim
endif

function! FontSizePlus ()
    let l:gf_size_whole = matchstr(&guifont, '\(:h\)\@<=\d\+$')
    let l:gf_size_whole = l:gf_size_whole + 1
    let l:new_font_size = ':h'.l:gf_size_whole
    let &guifont = substitute(&guifont, ':h\d\+$', l:new_font_size, '')
endfunction

function! FontSizeMinus ()
    let l:gf_size_whole = matchstr(&guifont, '\(:h\)\@<=\d\+$')
    let l:gf_size_whole = l:gf_size_whole - 1
    let l:new_font_size = ':h'.l:gf_size_whole
    let &guifont = substitute(&guifont, ':h\d\+$', l:new_font_size, '')
endfunction

nnoremap <c-kPlus> :call FontSizePlus()<CR>
nnoremap <c-kMinus> :call FontSizeMinus()<CR>
