" Créditos: https://devel.tech/snippets/n/vIIMz8vZ/load-vim-source-files-only-if-they-exist/
function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
	"else
	"echo "Não existe o arquivo:"  a:file
  endif
endfunction

call SourceIfExists("~/dev/dotfiles/vim/base.vim")
call SourceIfExists("~/dev/dotfiles/vim/base-dotfiles.vim")
call SourceIfExists("~/dev/dotfiles/vim/plugins.vim")
call SourceIfExists("~/.extra.vim")
