" autor: nenitf
" A partir de vim-bootstrap b0a75e4
" motivacional: https://www.youtube.com/watch?v=XA2WjJbmmoM

" Crédito: https://devel.tech/snippets/n/vIIMz8vZ/load-vim-source-files-only-if-they-exist/
function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
	"else
	"echo "Não existe o arquivo:"  a:file
  endif
endfunction

call SourceIfExists("~/dev/dotfiles/vim/.base.vim")
call SourceIfExists("~/dev/dotfiles/vim/.macros.vim")
call SourceIfExists("~/dev/dotfiles/vim/.plugs.vim")
call SourceIfExists("~/dev/dotfiles/vim/.so-linux.vim")
call SourceIfExists("~/dev/dotfiles/vim/.so-windows.vim")
call SourceIfExists("~/dev/dotfiles/vim/.oab.vim")
call SourceIfExists("~/.extra.vim")

" win32 talvez sozinho
""if has("win32")
""	set pythonthreedll=/c/Users/fcsilva/AppData/Local/Programs/Python/Python37/python37.dll
""	set pythondll=/c/Users/fcsilva/AppData/Local/Programs/Python/Python37/python37.dll
""else
""	set pythonthreedll=/c/Users/fcsilva/AppData/Local/Programs/Python/Python37/python37.dll
""	set pythondll=/c/Users/fcsilva/AppData/Local/Programs/Python/Python37/python37.dll
""endif
