# com o vim, <c-j> ou o g:vrc_trigger no método http
# https://github.com/diepm/vim-rest-console.git

http://localhost:3333
--
--
GET /appointments
--
POST /appointments
{
  "provider": "Felipe",
  "date": "2020-05-07T20:34:03"
}
