highlight Normal guifg=white guibg=black

set guioptions-=T  " tool bar
set guioptions-=m  " menu bar
set guioptions-=r  " scroll bar direita
set guioptions-=L  " scroll bar esquerda quando a janela possuir split vertical

if has("win32")
    " Alerts
    " http://vimdoc.sourceforge.net/htmldoc/gui_w32.html
    au GUIEnter * simalt ~x
    set guifont=Consolas:h11
else
    set guifont=UbuntuMono\ NF:h11
endif
